### ISSUE TITLE
Improve doc

### ISSUE THREAD

**Issue by hugoskwirrel** [transitive-bullshit/create-react-library#126]
Hello,

I think the documentation should mention that you need to run the following commands after cloning a repository created with `create-react-library`:

```sh
npm link
cd example
npm link <library-name>
npm i
```

The `npm link` commands need to be ran once, so when changes are made in the `src` directory, the module is rebuilt and the example app is refreshed.

Those commands are ran automatically when running `create-react-library` However, they need to be ran manually if you clone an existing repository.

**Comment by paulmelnikow** [comment]
Huh, is that reproducible in a new install? That sounds more like a bug to me.

**Comment by hugoskwirrel** [comment]
Hi,

This problem only occures when cloning an existing repository.

I think this is because the `npm link`s are ran during the `create-react-library` command, and of course you don't run this command when you clone an existing repos on a new machine.

Steps to reproduce:

- Run `create-react-library`
- do some stuffs in your new library 
- `git push`

Now on another machine:

```
git clone <your repository>
npm install
npm start
cd example
npm install
npm start
```

Now if you make changes in your `src` folder (in the new machine), the example app is not refreshed. To fix this, you need to run `npm link`.

**Comment by transitive-bullshit** [comment]
This is different for `npm` versus `yarn`. We're using `file:..` for `npm` and `link:..` for `yarn` which gets around the need to run `npm link` or `yarn link` at all since this is a common area that people forget.

it's not perfect, however, as if you use npm versus yarn and the original author used the other, this logic will fail, but a better default will be coming soon in CRL v2.

Thanks!
