### ISSUE TITLE
Production mode

### ISSUE THREAD

**Issue by jacarma** [transitive-bullshit/create-react-library#135]
The [Optimizing Performance](https://reactjs.org/docs/optimizing-performance.html#rollup) guide from react recommends to  rewrite "pocess.env.NODE_ENV" using "rollup-plugin-replace" like:
```
require('rollup-plugin-replace')({
    'process.env.NODE_ENV': JSON.stringify('production')
  }),
```
It may be good to have it by default.

Thanks a lot for this tool, I really like it :)

**Comment by transitive-bullshit** [comment]
Thanks for your contribution @jacarma!

I don't think this belongs in CRL, however, because it's aimed at creating reusable react libraries that can be used in different contexts, including during development.

This type of optimization is a better fit for the applications which are using your library as opposed to the library itself.

See my previous comment [here](https://github.com/transitive-bullshit/create-react-library/pull/65#issuecomment-422986302) for more info on why CRL doesn't minify its bundle by default.
