### ISSUE TITLE
this is too awesome

### ISSUE THREAD

**Issue by sw-yx** [transitive-bullshit/create-react-library#15]
this is very awesome!

only weird thing is it took much longer for me to do `yarn install and yarn link` than `npm install and npm link` which is very weird. 

i am making all new libraries with this thing. no complaints yet!

**Comment by transitive-bullshit** [comment]
Thanks dude -- glad to hear you're finding the project useful!

I agree I'm surprised that `yarn` seems to be slower for you than `npm`. Which versions of `yarn` and `npm` and `node` are you using locally and on which system?

Also, don't forget to star the repo to help others find it 👍

**Comment by sw-yx** [comment]
starred.

yarn 1.2.0
npm 6.0.0
node 8.5.0

its not a big deal but there was probably something i didnt understand about yarn or a randomly very shitty internet connection (doubt it tho, cos i just ctrl + C'ed and switched from yarn to npm and it was way faster that one time)

**Comment by transitive-bullshit** [comment]
I see what's going on; with `yarn`, we're installing deps both at the module root and `example/` since `yarn` supports `link:..` to reference the parent module. We can't do this with `npm` because before v6.0.0, it required your module to be published before you could link to it. So `npm` appears faster because we're only running `npm install` and `npm link` from the module root and not initializing the `example/` at all.

As of npm v6, npm now supports `file:..` syntax for package.json which is analogous to yarn's `link:..` syntax (these subtle differences are killing me lol), but I'm not sure we want to require npm >= 6 yet.

**Comment by transitive-bullshit** [comment]
This should now be resolved with `v2.3.7`.  Thanks @sw-yx!
