### ISSUE TITLE
Nothing happens after create-react-library

### ISSUE THREAD

**Issue by gsavvid** [transitive-bullshit/create-react-library#27]
Hello,

I've installed the package and then executed `create-react-library` but the command just exits without any message. No prompts, no errors. I've tried that on Ubuntu 16.04 with node version 6.9.5. Any help would be greatly appreciated.

**Comment by transitive-bullshit** [comment]
This is indeed worrisome. I have an idea of what's going on but can't reproduce it locally.

In the meantime, if you upgrade node to at least >= 8.0.0, it should work fine.

What I believe is happening is that if you're using an older version of node (< 8.0.0), we use [npx](https://github.com/zkat/npx) to temporarily install a newer version of node and run the program. From your description, it appears that npx is failing to install.  Can you verify that you can install and run npx separately from create-react-library?  That'll help me to narrow down the possible root cause here.

**Comment by bflemi3** [comment]
This was happening for me because I was behind a corporate firewall. Tethered with my phone and all worked.
