### ISSUE TITLE
stray .eslintrc file in template/src/.eslintrc

### ISSUE THREAD

**Issue by ehaynes99** [transitive-bullshit/create-react-library#31]
Projects created have a `.eslintrc` file in the root, but also one under `src` that mentions mocha ( https://github.com/transitive-bullshit/create-react-library/blob/3d8af13fafd8cd0f56645e068ade8855ef139649/template/src/.eslintrc ).

As mocha isn't used in the project, I'm guessing this is just cruft.

**Comment by transitive-bullshit** [comment]
Thanks for catching this, @ehaynes99.

It's supposed to be `env: "jest"` instead of `env: "mocha"` in order to ensure linting passes for the jest unit tests in the `src/` directory.

This is definitely something that's borderline and could be removed.  Feel free to remove it in your projects.

Thanks again!

**Comment by transitive-bullshit** [comment]
I've updated the template accordingly :)
