### ISSUE TITLE
Jest testing with css modules

### ISSUE THREAD

**Issue by brunocramos** [transitive-bullshit/create-react-library#34]
Hi. First, awesome package - helps a lot creating libraries.
Now, I'm having issues with test with jest + css modules. Not sure if it's something with rollup or not,  but all elements inside the test comes with empty classes. A simple example:

```javascript
import React from 'react';
import { shallow, configure } from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';
import Badge from '../Badge';
configure({ adapter: new Adapter() });

...

it('has class for primary color', () => {
  const wrapper = shallow(<Badge primary />);
  console.log(wrapper.debug());
});

```

Shows me:
```html
<span className="" />
```

Tried making a few changes on Jest and rollup but with no success. Any clues?

**Comment by transitive-bullshit** [comment]
Thanks for the kind words, @brunocramos.

Are you able to link to your full source, or is it private?

Is the jest testing code in `src/` or in `example/src`?  One simple fix might be to just move it into `example/src` and treat your tests as normal `create-react-app` tests within the example instead of src so you're guaranteed that jest is working with the compiled version of your component(s) instead of the original source.  This should also be more faithful, since you really want to be testing your module as other users will see it.

Let me know if that helps :)

**Comment by brunocramos** [comment]
@transitive-bullshit Yeah, I uploaded the branch I'm using at this moment.
Here: https://github.com/radargovernamental/design-system/tree/feature/tests

Just go for "yarn run test". The file is located at src/js/components/atoms/__tests__/Badge.test.js. It will print a span with empty className.

I agree with being faithful using the example and that's a good idea, but then again the source itself wouldn't be tested. IMO, the best would be testing in both cases. Let's try making this one work, otherwise I might stick with the idea of using in the example.

**Comment by transitive-bullshit** [comment]
I would recommend moving your tests over to `example/`. I can't think of a single good reason not to, and that's how CRL was originally setup to piggyback off of create-react-app's already excellent testing support.

**Comment by brunocramos** [comment]
Ok, I'll take a look into it. Thanks!
