### ISSUE TITLE
Tree shaking not applying for css with modules enabled

### ISSUE THREAD

**Issue by brunocramos** [transitive-bullshit/create-react-library#39]
Not sure if it's a postcss or rollup config issue, but it seems that enabling modules for postcss makes our bundle export all css.
Consider this in my index.js
```jsx
export Badge from './js/components/atom/Badge';
export Text from './js/components/atom/Text';
```

In the example, if I do this:

```jsx
import { Text } from 'my-lib;
export default class App extends React.Component {
  render() {
    return (
      <Text>Hello</Text>
    );
  }
}
```
All css from Text and Badge are imported, if though only Text is being used:

![image](https://user-images.githubusercontent.com/4956907/42654268-7630a12c-85ee-11e8-843b-26861efa1192.png)

The JS tree shakes ok, this is happening only to css.

**Comment by transitive-bullshit** [comment]
I believe this is due to the way postcss modules extracts all of the styles to be inserted into the head once instead of trying to do this once per css file which is what would need to be done to tree-shake css.

Practically speaking, this should be much of an issue as CSS is relatively small compared to JS & image assets for most apps. However, if this is an issue for you, I'd recommend using a css-in-js approach which will work around this. You can also try bringing this issue up in the [rollup-plugin-postcss](https://github.com/egoist/rollup-plugin-postcss) repo.

Cheers!

**Comment by transitive-bullshit** [comment]
See this existing rollup-plugin-postcss [issue](https://github.com/egoist/rollup-plugin-postcss/issues/98).
