### ISSUE TITLE
Add more template options?

### ISSUE THREAD

**Issue by transitive-bullshit** [transitive-bullshit/create-react-library#4]
Some ideas:
- webpack vs rollup
- flow or typescript support
- prettier integration
...

I'd really like to keep the default template as minimal as possible, but people should be able to easily swap out different options if they want.  Thoughts / suggestions?

**Comment by tsiq-swyx** [comment]
one idea: add storybook?

**Comment by spredemann** [comment]
I've found this repo because you commented this on another issue: "It is also significantly simpler, with the resulting library template weighing in at only 14 files. This is largely because we use Rollup, which the community has generally settled on as a better choice for bundling libraries".

If this is the case then I don't know why offer the option to use webpack. I've just started using this and so far so good. I don't care about webpack vs rollup as long as this works and stays out of my way as I develop and publish. I'd love to see this project continue with minimal setup and boilerplate and focus on developer experience and great docs with good examples on how to expand beyond what's included for common scenarios.

I'm not sure if it's possible or how complicated it would be to implement but to me what's great about create-react-app is that it covers the most common use cases and is update-able. For anything extra you can either work your way around or eject.

**Comment by vitormalencar** [comment]
Great project btw 🎉
like @tsiq-swyx I also think that storybook would be a very nice add-on
would make possible to create react component-libs very easy with a good live style guide approach.

**Comment by transitive-bullshit** [comment]
I just added `typescript` as a template option in `v2.4.0`.

Would welcome a PR adding storybook support to the `default` template! :)

**Comment by vitormalencar** [comment]
I will be happy to do it =) @transitive-bullshit

**Comment by medv** [comment]
storybook and cosmos implementation would be great. We are going to be going over that, including graphql implementation, so there might be something to contribute.

**Comment by zachwolf** [comment]
Would you see value in adding the option to provide `template` with a directory path, rather than picking from the provided examples?

The `default` template gets me 99% of the way to our ideal setup, but all our components need some tweaks in `package.json` to work in our companies eco system. Adding the ability to  run something like `$ create-react-library -t packages/component-template` could greatly increase the flexibility without having to standardize the given template across the global npm ecosystem. I think it'd be a pretty minimal change and would mirror create-react-app's `--scripts-version` flag.

Thoughts? If it seems of value, I can take on the work.

**Comment by transitive-bullshit** [comment]
@zachwolf Yeah, this is a very reasonable request. Feel free to submit a PR :)

**Comment by sag1v** [comment]
Is there any way to integrate `prettier` with `eslint` at the moment? i usually run `eslint --fix` along side with [prettier-eslint-cli](https://github.com/prettier/prettier-eslint-cli).  
But i'm struggling to do it with `create-react-library`. :confused:

**Comment by transitive-bullshit** [comment]
There's no built-in option to enable `prettier`, though I wouldn't expect it to be too complicated to add it to the default template's results.

There's more than one way to enable prettier which is one of the main reasons it hasn't been added by default yet in much the same way that prettier hasn't been added as a default to CRA.

At the same time, PRs are more than welcome if you have an integration that would help the community in general 👍

**Comment by transitive-bullshit** [comment]
@sag1v otherwise, please open a separate issue specific to your usage of `prettier` where the community can respond with best practices that're recommended in terms of enabling prettier support.

Thanks!

**Comment by stereobooster** [comment]
- prettier with default configuration (instead of standardjs)
- microbundle, which hides complexity of rollup
- eslint-config-react-app
- lint-staged with eslint and prettier https://prettier.io/docs/en/precommit.html
- docz + gh-pages

**Comment by transitive-bullshit** [comment]
@stereobooster these are all really reasonable suggestions -- really appreciate your feedback :)

I'll be updating CRL incrementally in the next week with some of these for sure 💯

If anyone is interested in adding PRs for `microbundle`, `eslint-config-react-app`, or `.travis.yml`, I think those are going to be easier changes to make.

**Comment by stereobooster** [comment]
- https://github.com/ai/size-limit

**Comment by transitive-bullshit** [comment]
Let's KISS 😄
