### ISSUE TITLE
Webpack flavor

### ISSUE THREAD

**Issue by DavidHenri008** [transitive-bullshit/create-react-library#49]
Your project is really interesting and quite complete. The only reason that stops me from using it within our team is the use of Rollup instead of Webpack. I am not arguing which one is better I am just saying that a Webpack flavor would be an interesting add-on.

Thank you.

**Comment by transitive-bullshit** [comment]
I'd be happy to consider a well-written PR that adds a webpack template, though I'd like to balance this option with keeping CRL as simple as possible.

@DavidHenri008 I'm curious what actually prevents you from using the default template in CRL right now. Is it just the aversion of using Rollup versus Webpack, or is there any change to the default Rollup config that you'd need in order for your use case to work? I ask because 99% of people are able to use the default Rollup config out-of-the-box without any changes, and the whole Rollup vs Webpack thing ends up just being noise.

**Comment by transitive-bullshit** [comment]
Also, really appreciate the feedback 👍

**Comment by DavidHenri008** [comment]
My idea was to simply add a question in the setup if the user prefers Webpack or Rollup and then replace few files and script commands. But I do understand it would add some complexity/noise to the project.

The main reason I asked for this feature it's because we are a small team and we are fairly new to the React realm. Most of the examples and documentation we have seen are based on Webpack so having to learn two platforms seems a bit too much for the moment.

Thanks

**Comment by transitive-bullshit** [comment]
Tracking in #57
