### ISSUE TITLE
Building Modular Libraries

### ISSUE THREAD

**Issue by anmolmahatpurkar** [transitive-bullshit/create-react-library#63]
Can you add an example rollup configuration for building modular libraries?

##### Multiple imports Right Now- 
```
import { A, B } from 'package';
```

##### With Modular Imports - 
```
import A from 'package/A'; 
import B from 'package/B';
```

^ This approach helps reduce the bundle size, as only the file needed is imported and added to the bundle.

**Comment by transitive-bullshit** [comment]
Yep -- see the readme section [Multiple Named Exports](https://github.com/transitive-bullshit/create-react-library#multiple-named-exports) 😄

**Comment by anmolmahatpurkar** [comment]
> Yep -- see the readme section [Multiple Named Exports](https://github.com/transitive-bullshit/create-react-library#multiple-named-exports) 😄

No, I am not asking about multiple named exports. I already checked this example.

So lets say there are two files in my src folder, ```Modal.js``` and ```Input.js```. I import both in index.js, and export them for named exports.

### Case 1: 

Now, when the package is built, the build folder contains only one index.js file with the code for both ```Modal.js``` and ```Input.js``` in one single file.

When using this package in a project, where code-splitting is enabled, if I ```import { Modal } from 'package';``` the code for Input.js will also be packed along, since its all in one single file.

### Case 2:

In this case, the built package should also two files, ```Modal.js``` and ```Input.js```, with the code for both component in two seperate files.

Now when using in a project, the user can import it like ```import Modal from 'package/Modal';```. Since this file only contains the code for the modal, other files wont be pack along, when code splitting. Thus reducing the bundle size.

### Benefits: 

^ This kind of a setup is useful when building a UI Library with many packages, while keeping the bundle size minimal.

Do you think we can configure this?

**Comment by transitive-bullshit** [comment]
Ahh, that makes more sense 😃you're more interested in supporting **tree shaking**.

> Do you think we can configure this?

Any modern bundler (webpack or rollup, for example) *should* handle tree shaking for you since we output to `esm` and `cjs` formats. Webpack, for instance, would favor the `esm` output by default and you *should* get tree-shaking for dead code removal without doing anything extra. Note that it *shouldn't* matter if your modules are in separate files or in one bundle, as we currently do.

Note my repeated use of the word **should**, because I'm not 100% confident this is the way things are currently working, and I'd love to follow-up with an investigation that tests this behavior in practice, perhaps against a CRA app that uses a CRL library with multiple exports where only one export is actually used.

@jdalton or @rich-harris are my expectations of tree-shaking performed by webpack / rollup correct at a high-level here?

**Comment by Rich-Harris** [comment]
I can't speak for webpack, but Rollup doesn't care whether you import 1 horse sized duck or 100 duck sized horses — treeshaking will work the same in both cases.

**Comment by transitive-bullshit** [comment]
Appreciate the prompt response @Rich-Harris 😄

**Comment by anmolmahatpurkar** [comment]
I agree that Rollup will handle the tree-shaking efficiently here. But, if I am not wrong, this handling will be done when the package is being built, i.e. before the package is published to NPM (or any other registry). 

In this case, while building, rollup will check and pack all the dependencies being used in the package's entry file, which in this case will be both ```Modal.js``` & ```Input.js```.

Now when you are using this package **inside a project**, the library is dependant on the **project's** bundler setup, which may or may not have tree shaking enabled.

### Possible Solution:

I explored the rollup docs a bit and came across the experimental code-splitting feature and configured this:

```javascript
import babel from 'rollup-plugin-babel';
import commonjs from 'rollup-plugin-commonjs';
import external from 'rollup-plugin-peer-deps-external';
import postcss from 'rollup-plugin-postcss';
import resolve from 'rollup-plugin-node-resolve';
import url from 'rollup-plugin-url';
import minify from 'rollup-plugin-babel-minify';

import pkg from './package.json';

export default {
	input: 'src/index.js',
	output: [
		{ dir: pkg.main, format: 'cjs', sourcemap: true, chunkFileNames: '[name].js' },
		{ dir: pkg.module, format: 'es', sourcemap: true, chunkFileNames: '[name].js' },
	],
	manualChunks: {
	        modal: ['src/modal/index.js'],
	        input: ['src/input/index.js'],
        },
	experimentalCodeSplitting: true,
	plugins: [
		external(),
		postcss({ modules: true }),
		url(),
		babel({ exclude: 'node_modules/**', plugins: ['external-helpers'] }),
		resolve(),
		commonjs(),
		minify({ removeConsole: true }),
	],
};

```

The ```manualChunks``` array contains paths that act as an entry point to build the chunks.

This resulted in the following files being built:

<img width="363" alt="screen shot 2018-09-18 at 3 10 32 pm" src="https://user-images.githubusercontent.com/36692003/45678900-0c6ec380-bb55-11e8-8a59-6ea94b01289a.png">
 
With this we can use ``` import Modal from 'package/modal';``` while ensuring code-splitting works in every project, irrespective of the bundle setup of that project. I think this is the kind of setup that is used in Lodash as well.

### Feedback

Let me know if you agree with this, and if there is anything else you would like me to add to it. If you think it may be useful, I can create a PR and add this to the examples of this repo.

Btw, thank you for the response and great work with the tool.

Also, @Rich-Harris thank you for your response. Love what you are doing with rollup. :)

**Comment by sag1v** [comment]
Just one small addition, It is important to verify that your babel config (`.babelrc`) is configured to:  
`"modules": false `

Because otherwise, babel will transplise the `import`s and `webpack`  or `rollup` wont get to do tree-shaking.

**Comment by transitive-bullshit** [comment]
@anmolmahatpurkar instead of code splitting which is relatively complex, if you want to achieve what you're aiming to achieve, I would recommend skipping `rollup` entirely and just running `babel` directly with 2 passes to convert your input sources to an `dist/es` and `dist/cjs` directories. This would retain the original files, just with the proper transpilation to the target directories. I've written about this as an alternative approach [here](https://hackernoon.com/7-different-ways-to-use-es-modules-today-fc552254ebf4).

With that being said, I'm not sure how I feel about incorporating this approach in `create-react-library` as the tradeoff seems to be adding complexity for what imho would result in very minimal functional gains. 95% of React libs will be consumed by webpack or rollup, which both contain reasonable tree shaking, and I'd rather keep the core bundling we do as simple as possible, with more advanced users such as yourself having the ability to take the boilerplate and tailor it to your needs.

I'm not at all convinced one way or another, however, so I'm happy to hear more discussion on this 💯

**Comment by anmolmahatpurkar** [comment]
@transitive-bullshit Agreed. I didn't mean to add the approach to the library. I said it may be helpful to add it to the examples of the repo. 

Anyways, This approach definitely depends on the use case. Would definitely checkout the alternatives as well. Thank you for you help! :)

**Comment by royipressburger** [comment]
@anmolmahatpurkar Im having the same issue, did you mange to solve it in a more generic way?

I have multiply component that I exported to a library, so doing what you did with the `manualChunks` is hard work since I have like 100 components.

And event with you solution, I tried to compile just 2 component and use only one of them in the project and I have encounter 2 problems: 
1. I could not do `import Modal from 'PackageName/Modal` because that file wasn't exists I had to do `from 'PackageName/dist/Modal`, is this what you mean in you example?
2. Still the second component was in my final bundle of the project. I am using webpack on the project So I guess im missing something,

**Comment by transitive-bullshit** [comment]
Closing as out of date since the `v3` release changes nearly everything about CRL.

**Comment by thefran1412** [comment]
Is there any way to achieve what was being discussed in `v3`?

**Comment by luisfernandezelectric** [comment]
> Closing as out of date since the `v3` release changes nearly everything about CRL.

Does this mean that now it IS possible to do what was asked in this issue? `import Foo from 'packageName/Foo'` 

I've been trying to achieve this with no luck, no any help will be much appreciated!!

**Comment by Eskaaa** [comment]
> > Closing as out of date since the `v3` release changes nearly everything about CRL.
> 
> Does this mean that now it IS possible to do what was asked in this issue? `import Foo from 'packageName/Foo'`
> 
> I've been trying to achieve this with no luck, no any help will be much appreciated!!

I also try to achieve it. I also try to achieve it. Without success. An example would be really helpful, the google search terms that come to my mind do not go any further due to the ambiguous terms.

**Comment by sandren** [comment]
Has anyone discovered a way to achieve this? 😅
