### ISSUE TITLE
Different README for repo and npm

### ISSUE THREAD

**Issue by sag1v** [transitive-bullshit/create-react-library#71]
Hi, is there any way to create different README file for the giyhub repo and `npm`? or maybe just exclude some parts from the `npm` README version.  

One use case is if you want to add some development related info to the README, such as instructions on how to run or build the library, or contribution info. Things that you are not necessarily want to show up on `npm` .

*Without impairing the ability to use one template*

**Comment by transitive-bullshit** [comment]
Thanks for the question @sag1v 👍 

As far as I know, there is no way to have different readmes on GitHub vs npm. Every project I know of has a consistent readme for both, and as a developer, I think this is good from a consistency of expectations perspective. You may not use npm as your source for building / installing, but some other people, particularly GitLab users, may prefer having the official readme on GitHub.

One way to do what you want (though I don't recommend it) is to have a different `readme.md` when you `npm publish` since the content on npm is strictly unrelated to the content on GitHub. E.g, whatever is in your local package when you publish will go to npm but that doesn't necessarily have to line up one-to-one with the source on GitHub.

With that being said, I think this is a really bad practice and would encourage you to just make your readme simpler in the first place. There's nothing preventing you from having a simple-ish readme and having that readme link to other markdown files that go into more detail on certain aspects of your module's usage of inner workings.

Hope this helps 😄

**Comment by sag1v** [comment]
@transitive-bullshit Fair enough :)

**Comment by chharvey** [comment]
check out jQuery’s [readme on github](https://github.com/jquery/jquery/tree/3.3.1) versus its [readme on npm](https://www.npmjs.com/package/jquery/v/3.3.1). can anyone explain how they did that?

**Comment by levrik** [comment]
@chharvey Probably swapping the files via a script before publishing it to npm.

**Comment by JuroOravec** [comment]
Just came across this. For future seekers, indeed jQuery uses a [template](https://github.com/jquery/jquery/tree/358b769a00c3a09a8ec621b8dcb2d5e31b7da69a/build/fixtures), and [populates it with current info and uses that as the distribution's README](https://github.com/jquery/jquery/blob/358b769a00c3a09a8ec621b8dcb2d5e31b7da69a/build/release/dist.js#L108).

**Comment by m10rten** [comment]
Found this while searching for it: add the original readme you want to display on github to the `.github` folder
the README.md in the root will then be displayed on npm.
